name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Frontend
        run: |
          cd /opt/energy-staging/energy_frontend
          git pull

      - name: Pull Backend
        run: |
          cd /opt/energy-staging/energy_backend
          git checkout staging
          git pull origin staging 

      - name: Redeploy Docker Compose
        run: |
          cd /opt/energy-staging/energy_backend
          docker compose -f docker-compose.prod.yml down -v && docker compose -f docker-compose.prod.yml up -d --build